# Generated by Django 2.0 on 2021-01-18 14:02

import collection.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20210118_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=collection.models.get_image_path)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='collection.Thing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
