# Generated by Django 2.2.9 on 2021-01-20 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='created',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='updated',
        ),
        migrations.AlterField(
            model_name='social',
            name='thing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='collection.Thing'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='thing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='collection.Thing'),
        ),
    ]
